// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHmsShZ9eTBIbFj2JC5FRW2LFyxutopZ4',
    appId: '1:879929112778:web:3a05d04b6a7d8ed78e9c33',
    messagingSenderId: '879929112778',
    projectId: 'ourapp-7b3f5',
    authDomain: 'ourapp-7b3f5.firebaseapp.com',
    storageBucket: 'ourapp-7b3f5.appspot.com',
    measurementId: 'G-1R0S2TB2E5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6dVu2XwwQoddnlcvPLHJOGGWJLoUfQeM',
    appId: '1:879929112778:android:2c4cf75e574530ae8e9c33',
    messagingSenderId: '879929112778',
    projectId: 'ourapp-7b3f5',
    storageBucket: 'ourapp-7b3f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyzdsWLwGvRFXbG1-AUY1bgDW3kYgLpZg',
    appId: '1:879929112778:ios:0a7adb99c156c9de8e9c33',
    messagingSenderId: '879929112778',
    projectId: 'ourapp-7b3f5',
    storageBucket: 'ourapp-7b3f5.appspot.com',
    iosBundleId: 'com.example.barber',
  );
}
